remove validate step

diff --git a/.github/workflows/labeled_tests.yml b/.github/workflows/labeled_tests.yml
--- a/.github/workflows/labeled_tests.yml
+++ b/.github/workflows/labeled_tests.yml
@@ -30,13 +30,13 @@ jobs:
           echo "JSON_LABELS_ALL: ${JSON_LABELS_ALL}"
         env:
           ALL_LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
-      - name: Validate labels
-        run: |
-          echo "labels: ${{ steps.labels-to-json.outputs.all-labels }}"
-          if [ "${{ steps.labels-to-json.outputs.all-labels }}" = "" ]; then
-            echo "No labels found. Failing workflow."
-            exit 1
-          fi
+      # - name: Validate labels
+      #   run: |
+      #     echo "labels: ${{ steps.labels-to-json.outputs.all-labels }}"
+      #     if [ "${{ steps.labels-to-json.outputs.all-labels }}" = "" ]; then
+      #       echo "No labels found. Failing workflow."
+      #       exit 1
+      #     fi
 
   pytest:
     needs: [labels-to-json]
